-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 15/08/2024 às 03:08
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `mapamundi`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `paises`
--

CREATE TABLE `paises` (
  `nome` varchar(100) NOT NULL,
  `capital` varchar(100) NOT NULL,
  `populacao` varchar(255) NOT NULL,
  `politica` varchar(100) NOT NULL,
  `idh` varchar(255) NOT NULL,
  `presidente` varchar(100) NOT NULL,
  `idioma` varchar(100) NOT NULL,
  `pib` varchar(255) NOT NULL,
  `moeda` varchar(100) NOT NULL,
  `territorio` varchar(255) NOT NULL,
  `bandeira` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `paises`
--

INSERT INTO `paises` (`nome`, `capital`, `populacao`, `politica`, `idh`, `presidente`, `idioma`, `pib`, `moeda`, `territorio`, `bandeira`) VALUES
('Afeganistão', 'Pastó/Dari', '41,13 milhões', 'República islâmica', '0,352', 'Mohammad Ashraf Ghani', 'Cabul', '14,27 Bi USD', 'Afegane afegão (AFN)', '652.860 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/125px-Flag_of_the_Taliban.svg.png'),
('África do Sul', 'Pretória', '57.780.000', 'República Constitucional e parlamentarista', '0.717', 'Cyril Ramaphosa', 'Língua africanêr e inglês', '405,3 bilhões USD', 'Rand sul-africano', '1.221.037km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/125px-Flag_of_South_Africa.svg.png'),
('Albânia', 'Tirana', '2,8 milhões', 'Capitalista', '0.795', 'Bajram Begaj', 'Albanês', '$15,28 bilhões', 'Lek albanês (ALL)', '28.748 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/albania.jpg'),
('Alemanha', 'Berlim', '83 milhões', 'Capitalista', '0.947', 'Frank-Walter Steinmeier', 'Alemão', '$4,5 trilhões', 'Euro (EUR)', '357.386 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/alemanha.jpg'),
('Andorra', 'Andorra a Velha', '77 mil', 'Capitalista', '0.858', 'Xavier Espot Zamora', 'Catalão', '$3,15 bilhões', 'Euro (EUR)', '467,63 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/andorra.jpg'),
('Angola', 'Luanda', '30.810.000', 'República presidencialista', '0.591', 'João Lourenço', 'Português', '106,8 bilhões USD', 'Kwanza', '1.246.700km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/188px-Flag_of_Angola.svg.png'),
('Anguilla', 'Vale', '15.094', 'Monarquia Parlamentarista, Território Dependente', '0.865', 'Carlos III', 'Inglês', '32 milhões USD', 'Dólar do Caribe Oriental', '91 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/125px-Flag_of_Anguilla.svg.png'),
('Antígua e Barbuda', 'Saint John', '93.763', 'Parlamentarismo, Monarquia Constitucional Federal', '0.798', 'Rei Charles', 'Inglês', '1,868 bilhão USD', 'Dólar do Caribe Oriental', '440 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/125px-Flag_of_Antigua_and_Barbuda.svg.png'),
('Arábia Saudita', 'Árabe', '36,41 milhões', 'monarquia absoluta islâmica', '0,752', 'Salman', 'Riad', '1,109 Tri USD', 'Riyal Saudita (SAR)', '2.150.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png'),
('Argélia', 'Argel', '45.000.000', 'República semipresidencialista', '0.745', 'Abdelmadjid Tebboune', 'Árabe, Berbere e Francês', '165 bilhões USD', 'Dinar argelino', '2.381.741 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/188px-Flag_of_Algeria.svg.png'),
('Argentina', 'Buenos Aires', '46.23 milhões', 'República federal presidencialista', '0.849', 'Javier Milei', 'Espanhol', '631.1 Bilhões de Dólares', 'Peso argentino', '2.78 milhões km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/188px-Flag_of_Argentina.svg.png'),
('Armênia', 'Armênio', '2,9 milhões', 'República Semipresidencialista', '0,776', 'Vahagn Khachaturyan', 'Yerevan', '13 Bi USD', 'Dram Armênio (AMD)', '29.743Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/125px-Flag_of_Armenia.svg.png'),
('Austrália', 'Camberra', '27, 195 mi', 'Monarquia constitucional parlamentarista', '0.951', 'Rei Carlos III', 'Inglês', ' 1,61 tri USD', 'Dólar australiano', '7,6 mil km2', 'https://s3.static.brasilescola.uol.com.br/be/2022/01/bandeira-da-australia.jpg'),
('Áustria', 'Viena', '8,9 milhões', 'Capitalista', '0.922', 'Alexander Van der Bellen', 'Alemão', '$480,4 bilhões', 'Euro (EUR)', '83.879 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/austria.jpg'),
('Azerbaijão', 'Azerbaijano', '10 milhões', 'Republica presidencialista', '0,756', 'Ilham Aliyev', 'Baku', '54 Bi USD', 'Dinar bareinita(BHD)', '86.600Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/125px-Flag_of_Azerbaijan.svg.png'),
('Bahamas', 'Nassau', '417.456', 'Estado unitário, Parlamentarismo, Monarquia parlamentarista', '0.784', 'Chet Neymour', 'Inglês', '12,9 bilhões USD', 'Dólar bahamense', '13.940 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/800px-Flag_of_the_Bahamas.svg.png'),
('Bahrain', 'Árabe', '1,5 milhões', 'Monarquia constitucional', '0,852', 'Hamad bin Isa al-Khalifa (rei)', 'Manama', '38 Bi USD', 'Dinar bareinita(BD)', '780Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/125px-Flag_of_Bahrain.svg.png'),
('Bangladesh', 'Bengali', '166 milhões', 'República parlamentarista', '0,661', 'Mohammed Shahabuddin', 'Daca', '411 Bi USD', 'Taka bengali', '147.570Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/125px-Flag_of_Bangladesh.svg.png'),
('Barbados', 'Bridgetown', '281.635', 'República Parlamentarista', '0.788', 'Sandra Mason', 'Inglês', '5,7 bilhões USD', 'Dólar barbadense', '430 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/125px-Flag_of_Barbados.svg.png'),
('Bélgica', 'Bruxelas', '11,5 milhões', 'Capitalista', '0.919', 'Alexander De Croo', 'Neerlandês', '$593,9 bilhões', 'Euro (EUR)', '30.689 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/belgica.jpg'),
('Belize', 'Belmopã', '405.272 ', 'Democracia Parlamentar', '0.694', 'Charles III', 'Inglês', '2,831 bilhões USD', 'Dólar belizenho', '22.966 km²', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg'),
('Benin', 'Porto Novo', '13.000.000', 'República presidencialista', '0.504', 'Patrice Talon', 'Francês', '17,36 bilhões USD', 'Franco CFA Central', '114.763 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/188px-Flag_of_Benin.svg.png'),
('Bermudas', 'Hamilton', '63.913', 'Território Britânico Ultramarino', '0,930', 'Rena Lalgie', 'Inglês', '117 mil USD', 'Dólar bermudense', '53,3 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/188px-Flag_of_Bermuda.svg.png'),
('Bielorússia', 'Minsk', '9,4 milhões', 'Economia mista', '0.808', 'Alexander Lukashenko', 'Bielorrusso', '$80,9 bilhões', 'Rublo bielorrusso (BYN)', '207.600 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/bielorrussia.jpg'),
('Bolívia', 'Sucre', '12,22 milhões ', 'República presidencialista unitária', '0.703', 'Luis Arce', 'Espanhol', '44,01 Bilhões de Dólares', 'Boliviano', '1.099.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/188px-Flag_of_Bolivia_%28state%29.svg.png'),
('Bósnia e Herzegovina', 'Saravejo', '3,2 milhões', 'Capitalista', '0.780', 'Željka Cvijanović', 'Bósnio', '$23,1 bilhões', 'Marco conversível da Bósnia (BAM)', '51.197 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/bosniaherzegovina.jpg'),
('Botsuana', 'Gaborone', '2.400.000', 'República parlamentarista', '0.708', 'Mokgweetsi Masisi', 'Inglês e Setswana', '18,35 bilhões USD', 'Pula', '581.730 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/255px-Flag_of_Botswana.svg.png'),
('Brasil', 'Brasília', '211 milhões ', 'República federativa presidencialista', '0.760', 'Luiz Inácio Lula da Silva', 'Português', '1.92 Trilhão de Dólares ', 'Real', '8.51 milhões km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1200px-Flag_of_Brazil.svg.png'),
('Brunei', 'Malaio', '450 mil', 'Monarquia Absoluta', '0,838', 'Hassanal Bolkiah (Ditador)', 'Bandar Seri Begawan', '13 Bi USD', 'Dólar Bruneano', '5.765Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/125px-Flag_of_Brunei.svg.png'),
('Bulgária', 'Sofia', '6,9 milhões', 'Capitalista', '0.795', 'Rumen Radev', 'Búlgaro', '$83,9 bilhões', 'Lev búlgaro (BGN)', '110.994 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/bulgaria.jpg'),
('Burkina Faso', 'Uagadugu', '22.000.000', 'República semipresidencialista', '0.449', 'Ibrahim Traoré', 'Francês e Mooré', '19,74 bilhões USD', 'Franco CFA Ocidental', '272.967 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/255px-Flag_of_Burkina_Faso.svg.png'),
('Burundi', 'Gitega', '13.000.000', 'República presidencialista', '0.426', 'Évariste Ndayishimiye', 'Kirundi, Francês e Inglês', '3,17 bilhões USD', 'Franco Burundiano', '27.834 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/800px-Flag_of_Burundi.svg.png'),
('Butão', 'Dzongkha', '770 mil', 'Monarquia constitucional', '0,654', 'Jigme Khesar Namgyal', 'Timbu', '2,5 Bi USD', 'Ngultrum(BTN)', '38.394Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/125px-Flag_of_Bhutan.svg.png'),
('Cabo Verde', 'Praia', '593.149', 'República semipresidencialista unitária', '0.661', 'José Maria Neves', 'Português', '2,227 bilhões USD', 'Escudo cabo-verdiano', '4.033 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/255px-Flag_of_Cape_Verde.svg.png'),
('Camarões', 'Yaoundé', '27.910.000', 'República Presidencialista', '0.587', 'Paul Biya', 'Francês e Inglês', '43,64 bilhões USD', 'Franco CFA Central', '475.442 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/255px-Flag_of_Cameroon.svg.png'),
('Cambodja', 'Khmer', '16 milhões', 'Monarquia constitucional', '0,594', 'Hun Sen', 'Phnom Penh', '27 Bi USD', 'Riel', '181.035Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/125px-Flag_of_Cambodia.svg.png'),
('Canadá', 'Ottawa', '38,93 milhões ', 'República Federal Presidencialista', '0.888', 'Justin Trudeau', 'Francês, Inglês', '2,138 trilhões USD', 'dólar canadense', '9.985.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png'),
('Catar', 'Árabe', '2,9 milhões', 'Monarquia Absoluta', '0,848', 'Tamim bin Hamad al-Thani', 'Doha', '192 Bi USD', 'Rial Catariano', '11.586Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png'),
('Cazaquistão', 'Cazaque/Russo', '19 milhões', 'república presidencialista', '0,825', 'Kassym-Jomart Tokayev', 'Nursultan', '182 Bi USD', 'Tenge cazaque', '2.724.900Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/125px-Flag_of_Kazakhstan.svg.png'),
('Chade', 'Djamena', '17.500.000', 'República unitária sob regime militar', '0.295', 'Mahamat Déby Itno', 'Francês e Árabe', '12,7 bilhões USD', 'Franco CFA Central', '1.284.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg'),
('Chile', 'Santiago', '19.6 milhão', 'República unitária presidencialista', '0.855', 'Gabriel Boric', 'Espanhol', '301 Bilhão de Dólares', 'Peso chileno', '756,626 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/188px-Flag_of_Chile.svg.png'),
('China', 'Mandarim', '1,4 bilhões', 'Estado socialista unipartidário', '0,768', 'Xi Jinping', 'Pequim', '17,7 Tri USD', 'Yuan(CNY)', '9.596.961 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/125px-Flag_of_the_People%27s_Republic_of_China.svg.png'),
('Chipre', 'Nicósia', '1,19 milhão', 'Capitalista', '0.856', 'Nicos Anastasiades', 'Grego', 'US$ 21,88 bilhões', 'Euro (EUR)', '9.251 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/chipre.jpg'),
('Colômbia', 'Bogotá', '51.87 milhões', 'República presidencialista unitária', '0.767', 'Gustavo Petro', 'Espanhol', '343.6 Bilhão de Dólares', 'Peso colombiano', '1.142 milhões km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/188px-Flag_of_Colombia.svg.png'),
('Comores', 'Moroni', '836.774', 'República federal Presidencialista', '0.586', 'Azali Assoumani', 'Comoriano, Árabe e Francês', '1,243 bilhão USD', 'Franco comoriano', '2.235 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/800px-Flag_of_the_Comoros.svg.png'),
('Congo', 'Brazzaville', '5.970.000', 'República Semipresidencialista Unitária', '0.593', 'Denis Sassou Nguesso', 'Francês', '15,82 bilhões USD', 'Franco CFA Central', '342.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/125px-Flag_of_the_Republic_of_the_Congo.svg.png'),
('Coreia do norte', 'Coreano', '25 milhões', 'Estado socialista unipartidário', '0,595', 'Kim Jong-un', 'Pyongyang', '40 Bi USD', 'Won', '120.540Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/125px-Flag_of_North_Korea.svg.png'),
('Coreia do sul', 'Coreano', '51 milhões', 'Republica presidencialista', '0,929', 'Yoon Suk-yeol', 'Seul', '1,8 Tri USD', 'Won', '100.210 Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png'),
('Costa do Marfim', 'Yamussucro', '28.160.000', 'República presidencial multipartidária', '0.534', 'Alassane Ouattara', 'Francês', '70,02 bilhões USD', 'Franco CFA ocidental', '322.462 km²', 'https://abrasoffa.org.br/wp-content/uploads/2022/02/Costa-do-Marfim.png'),
('Costa Rica', 'San José', '5,181 milhões', 'Presidencialista unitário', '0.809', 'Rodrigo Chaves', 'Espanhol', '69,24 bilhões USD', 'Colón costarriquenho', '51.100 km²', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg'),
('Croácia', 'Zagreb', '4,15 milhão', 'Capitalista', '0.838', 'Zoran Milanović', 'Croata', 'US$ 66,08 bilhões', 'Kuna Croata', '56.594 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/croacia.jpg'),
('Cuba', 'Havana', '11,21 milhões', 'República, Estado unitário, Presidencialismo, Estado socialista, Semipresidencialismo', '0.863', 'Miguel Díaz-Canel', 'Espanhol', '633,4 bilhões USD', 'Peso cubano', '109.884 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/800px-Flag_of_Cuba.svg.png'),
('Dinamarca', 'Copenhague', '5,85 milhão', 'Capitalista', '0.930', 'Mette Frederiksen', 'Dinamarquês', 'US$ 357,9 bilhões', 'Coroa Dinamarquesa', '43.098 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/dinamarca.jpg'),
('Djibuti', 'Djibuti', '1.121.000', 'República semipresidencialista', '0.515', 'Ismaïl Omar Guelleh', 'Francês e Árabe', '3,515 bilhões USD', 'Franco do Djibouti', '23.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg'),
('Dominica', 'Roseau', '72.737', 'República Parlamentarista', '0.776', 'Luis Abinader', 'Inglês', '607,4 milhões USD', 'Dólar do Caribe Oriental', '754 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/1200px-Flag_of_Dominica.svg.png'),
('Egito', 'Cairo', '111.000.000', 'República Democrática', '0.728', 'Abdul Fatah Khalil Al-Sisi', 'Árabe', '476,7 bilhões USD', 'Libra egípcia', '1.002.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/255px-Flag_of_Egypt.svg.png'),
('El Salvador', 'São Salvador', '6,336 milhões', 'Presidencialismo, República constitucional', '0.659', 'Nayib Bukele', 'Espanhol', '32,49 bilhões USD', 'Dólar americano, Bitcoin', '21.040 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/800px-Flag_of_El_Salvador.svg.png'),
('Emirados Árabes Unidos', 'Árabe', '9,8 milhões', 'Monarquia Federal', '0,89', 'Mohammed bin Zayed Al Nahyan', 'Abu Dhabi', '501 Bi USD', 'Dirham dos Emirados Árabes Unidos', '83.600Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/125px-Flag_of_the_United_Arab_Emirates.svg.png'),
('Equador', 'Quito', '18 milhões', 'República presidencialista', '0.740', 'Daniel Noboa', 'Espanhol', '115 Bilhões de Dólares', 'Dólar americano', '283.561 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/188px-Flag_of_Ecuador.svg.png'),
('Eritreia', 'Asmara', '3.684.000', 'República presidencialista unipartidária unitária', '0.493', 'Isaias Afewerki', 'Árabe, Tigrínio e Inglês', '2,065 bilhões USD', 'Nakfa', '117.600 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/255px-Flag_of_Eritrea.svg.png'),
('Escócia', 'Edimburgo', '5,5 milhões', 'Capitalista', '0.932', 'Rishi Sunak', 'Escocês gaélico', '$205 bilhões', 'Libra esterlina (GBP)', '77.910 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/escocia.jpg'),
('Eslováquia', 'Bratislava', '5,46 milhão', 'Capitalista', '0.844', 'Zuzana Čaputová', 'Eslovaco', 'US$ 110,01 bilhões', 'Euro (EUR)', '49.035 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/eslovaquia.jpg'),
('Eslovênia', 'Liubliana', '2,07 milhão', 'Capitalista', '0.892', 'Robert Golob', 'Esloveno', 'US$ 25,42 bilhões', 'Euro (EUR)', '20.273 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/eslovenia.jpg'),
('Espanha', 'Madri', '46,75 milhão', 'Capitalista', '0.923', 'Pedro Sánchez', 'Espanhol', 'US$ 1.311 trilhão', 'Euro (EUR)', '505.992 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/espanha.jpg'),
('Essuatíni', 'Mebabane', '1.202.000', 'Monarquia absoluta', '0.610', 'Ambrose Mandvulo Dlamini', 'Suázi e Inglês', '4,791 bilhões USD', 'Lilangeni suazi', '17.364 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/640px-Flag_of_Eswatini.svg.png'),
('Estados Federados da Micronésia', 'Palikir', '112,6 mil', 'República democrática presidencialista', '0.62', 'Wesley Simina', 'Inglês', ' 367 mi USD ', 'Dólar americano', '702 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/125px-Flag_of_the_Federated_States_of_Micronesia.svg.png'),
('Estados Unidos', 'Washington, D.C', '333,3 milhões', 'Federação, Presidencialismo, República federal, República constitucional', '0.944', 'Joe Biden', 'inglês', '25,44 trilhões USD ', 'Dólar Americano', '9.834.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg'),
('Estônia', 'Tallinn', '1,33 milhão', 'Capitalista', '0.867', 'Kaja Kallas', 'Estoniano', 'US$ 31,82 bilhões', 'Euro (EUR)', '43.297 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/estonia.jpg'),
('Etiópia', 'Addis Ababa', '123.400.000', 'República federal parlamentarista', '0.492', 'Sahle-Work Zewde', 'Amárico', '126,8 bilhões USD', 'Birr', '1.112.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg'),
('Fiji', 'Suva', '926,2 mil', 'República parlamentarista', '0.73', 'Wiliame Katonivere', 'Inglês, fijiano e híndi fijiano', ' 3 bi USD ', 'Dólar Fijiano', '18,3 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/125px-Flag_of_Fiji.svg.png'),
('Filipinas', 'Filipino/Inglês', '113 milhões', 'república presidencialista', '0,718', 'Bongbong Marcos', 'Manila', '402 Bi USD', 'Peso filipino (PHP)', '300.000Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/125px-Flag_of_the_Philippines.svg.png'),
('Finlândia', 'Helsinki', '5,52 milhão', 'Capitalista', '0.890', 'Sanna Marin', 'Finlandês', 'US$ 331,6 bilhões', 'Euro (EUR)', '338.424 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/finlandia.jpg'),
('França', 'Paris', '65,72 milhão', 'Capitalista', '0.901', 'Emmanuel Macron', 'Francês', 'US$ 2.922 trilhões', 'Euro (EUR)', '551.695 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/franca.jpg'),
('Gabão', 'Libreville', '2.389.000', 'República presidencialista', '0.693', 'Brice Oligui Nguema', 'Francês', '21,07 bilhões USD', 'Franco CFA Central', '267.667 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/1200px-Flag_of_Gabon.svg.png'),
('Gâmbia', 'Banjul', '2.766.000', 'República presidencialista', '0.502', 'Adama Barrow', 'Inglês', '2,017 bilhões USD', 'Dalasi', '11.300 km²', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg'),
('Gana', 'Acra', '31.730.000', 'República presidencialista', '0.632', 'Nana Akufo-Addo', 'Inglês', '74,26 bilhões USD', 'Cedi', '238.533 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/255px-Flag_of_Ghana.svg.png'),
('Geórgia', 'Tiblissi', '3,72 milhões', 'semipresidencialista', '0.784', 'Salome Zurabishvili', 'Georgiano', 'US$ 16,61 bilhões', 'Lari Georgiano (GEL)', '69.700 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/188px-Flag_of_Georgia.svg.png'),
('Granada', 'Saint Georges', '125.438', 'Parlamentarismo, Monarquia Parlamentarista', '0.779', 'Charles III', 'Inglês', '1,215 bilhão USD', 'Dólar do Caribe Oriental', '344 km²', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg'),
('Grécia', 'Atenas', '10,5 milhões', 'Capitalista', '0.888', 'Katerina Sakellaropoulou', 'Grego', '$209 bilhões', 'Euro (EUR)', '131.957 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/grecia.jpg'),
('Groelândia', 'Nuuk', '56.661', 'monárquico parlamentarista', '0.786', 'Rainha Margrethe II', 'Groenlandês', '3,236 bilhões USD', 'Coroa dinamarquesa', ' 2.166.000 km²', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxaDua5uq1ABh-2eZN2vhMAIkYBRtN0RU27hBlzA3MFTHfXhFCtv2h8equJQk&s=10'),
('Guadalupe', 'Basse Terre', '409.152', 'Estado Unitário, Semipresidencialismo', '0.681', 'Emmanuel Macron', 'Francês', '8,11 bilhões USD', 'Euro (EUR)', ' 1.628 km²', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Unofficial_flag_of_Guadeloupe_%28local%29.svg'),
('Guam', 'Aganha', '168.801', 'Território não incorporado dos Estados Unidos', 'Não encontrado', 'Lou Leon Guerrero', 'Inglês e chamorro', '2,5 Bilhões USD', 'Dólar dos Estados Unidos ', '541,3 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/188px-Flag_of_Guam.svg.png'),
('Guatemala', 'Cidade da Guatemala', '17,36 milhões', 'Estado unitário, Presidencialismo, República constitucional', '0.56', 'Bernardo Arévalo', 'Espanhol', '95 bilhões USD', 'Quetzal guatemalteco', '108.890 km²', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg'),
('Guiana', 'Georgetown', '808.726 ', 'República presidencialista', '0.611', 'Irfaan Ali', 'Inglês', '14,72 Bilhões de Dólares', 'Dólar guianense', '214.969 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/188px-Flag_of_Guyana.svg.png'),
('Guiana Francesa', 'Caiena', '301.099 ', 'Região e departamento ultramarino da República Francesa', '0.794', 'Emmanuel Macron', 'Francês', '15,36 Bilhões de Dólares', 'Euro', '84.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/188px-Flag_of_France.svg.png'),
('Guiné', 'Conacri', '13.530.000', 'República presidencialista', '0.477', 'Mamady Doumbouya', 'Francês', '12,76 bilhões USD', 'Franco guineense', '245.857 km²', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg'),
('Guiné Equatorial', 'Malabo', '1.403.000', 'República presidencialista', '0.592', 'Teodoro Obiang Nguema Mbasogo', 'Espanhol, Francês e Português', '10,02 bilhões USD', 'Franco CFA Central', '28.051 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/255px-Flag_of_Equatorial_Guinea.svg.png'),
('Guiné-Bissau', 'Bissau', '2.024.000', 'República semipresidencialista', '0.455', 'Umaro Sissoco Embaló', 'Português e Crioulo guineense', '1,643 bilhões USD', 'Franco CFA Ocidental', '36.125 km²', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg'),
('Haiti', 'Porto Príncipe', '11,58 milhões', 'República, Estado unitário, Semipresidencialismo', '0.51', 'Ariel Henry', 'Crioulo Haitiano, francês', '20,25 bilhões', 'Gourde haitiano', '27.750 km²', 'https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg'),
('Honduras', 'Tegucigalpa', '10,43 milhões', 'Estado unitário, Presidencialismo, República constitucional', '0.632', 'Xiomara Castro', 'Espanhol', '31,72 bilhões USD', 'Lempira hondurenha', '112.492 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/800px-Flag_of_Honduras.svg.png'),
('Hungria', 'Budapeste', '9,6 milhões', 'Capitalista', '0.854', 'Katalin Novák', 'Húngaro', '$199 bilhões', 'Forint (HUF)', '93.030 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/hungria.jpg'),
('Iêmen', 'Árabe', '33,7 milhões', 'República Democrática do Iêmen', '0,439', 'Rashad al-Alimi', 'Sana', '21,61 Bi USD', 'Rial iemenita (YER)', '555.000 km²', 'https://flagpedia.net/data/flags/w1600/ye.png'),
('Ilha de São Martinho', 'Marigot', '31.791', 'República Francesa', '0.901', 'Emmanuel Macron', 'Francês', '34 mil USD', 'Euro', '53,2 km²', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg'),
('Ilhas Cayman', 'George Town', '68.706', 'Parlamentarismo, Democracia Representativa, Monarquia Parlamentarista', 'sem número específico', 'Duncan Taylor', 'Inglês', '6,845 bilhões USD', 'Dólar das Ilhas Cayman', ' 259 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/800px-Flag_of_the_Cayman_Islands.svg.png'),
('Ilhas Faroe', 'Tórshavn', '50.451', 'Região autónoma da Dinamarca', '0,943', 'Frederico X', 'Feroês e dinamarquês', '1,56 milhões USD', 'Coroa feroesa', '1.399 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/188px-Flag_of_the_Faroe_Islands.svg.png'),
('Ilhas Malvinas', 'Stanley', '3.662', 'Território britânico ultramarino', '0,874', 'Alison Blake', 'Inglês', '96 mil USD', 'Libra das Malvinas', '12.200 km', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/188px-Flag_of_the_Falkland_Islands.svg.png'),
('Ilhas Marianas do Norte', 'Saipã', '55.650', 'Democracia representativa', 'não encontrado', 'Arnold Palacios', 'Inglês, chamorro e caroliniano', '858 milhões USD', 'dólar americano', '477 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/188px-Flag_of_the_Northern_Mariana_Islands.svg.png'),
('Ilhas Marshall', 'Dalap-Uliga-Darrit (Atol de Marujo)', '58,4 mil', 'República parlamentarista', '0.731', 'Hilda Heine', 'Marshalês e inglês', ' 153 mi USD ', 'Dólar americano', '181 km²', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg'),
('Ilhas Salomão', 'Honiara', '720,9 mil', 'Monarquia constitucional parlamentarista', '0.564', 'Rei Carlos III', 'Inglês', ' 658 mi USD ', 'Dólar das Ilhas Salomão', '28,9 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg'),
('Ilhas Turks e Caicos', 'Grand Turk', '45.703', 'Monarquia', '0.93', 'Rei Carlos III', 'Inglês', '1,139 bilhão USD', 'Dólar americano (USD)', '616 km²', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg'),
('Ilhas Virgens Americanas', 'Charlotte Amalie', '105.413', 'Federação, Presidencialismo, República Federal, República Constitucional', '0.944', 'Joe Biden', 'Inglês', '4,444 bilhões USD', 'Dólar americano', '346,4 km²', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg'),
('Ilhas Virgens Britânicas', 'Road Town', '31.305', 'Monarquia Constitucional', '0.944', 'Carlos III', 'Inglês', '500 milhões USD', 'Dólar americano', '153 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/125px-Flag_of_the_British_Virgin_Islands.svg.png'),
('Índia', 'Hindi/Inglês', '1,4 bilhões', 'República parlamentarista', '0,644', 'Draupadi Murmu', 'Nova Deli', '3,5 tri USD', 'Rupia indiana (INR)', '3.287.263Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/125px-Flag_of_India.svg.png'),
('Indonésia', 'Jacarta', '279,1 mi', 'República presidencialista', '0.6', 'Joko Widodo', 'Indonésio', ' 4,4 tri USD ', 'Rupia Indonésia', '1,9 mi km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png'),
('Inglaterra', 'Londres', '56 milhões', 'Capitalista', '0.932', 'Rishi Sunak', 'Inglês', '$3,2 trilhões', 'Libra esterlina (GBP)', '130.279 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/inglaterra.jpg'),
('Irã', 'Persa(Farsi)', '85 milhões', 'República Islâmica teocrática', '0,702', 'Mohammad Mokhber', 'Teerã', '231 Bi USD', 'Rial iraniano (IRR)', '1.648.195Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/125px-Flag_of_Iran.svg.png'),
('Iraque', 'Árabe/Curdo', '41 milhões', 'Republica parlamentarista', '0,674', 'Abdul Latif Rashid', 'Bagdá', '197 Mi USD', 'Dinar iraquiano (IQD)', '438.317Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/125px-Flag_of_Iraq.svg.png'),
('Irlanda', 'Dublin', '5,2 milhões', 'Capitalista', '0.955', 'Michael D. Higgins', 'Irlandês', '$559 bilhões', 'Euro (EUR)', '70.273 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/irlanda.jpg'),
('Irlanda do Norte', 'Belfast', '1,9 milhões', 'Capitalista', '0.932', 'Rishi Sunak', 'Inglês', '$55 bilhões', 'Libra esterlina (GBP)', '14.130 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/irlandadonorte.jpg'),
('Islândia', 'Reykjavik', '376 mil', 'Capitalista', '0.959', 'Guðni Th. Jóhannesson', 'Islandês', '$32 bilhões', 'Coroa islandesa (ISK)', '103.000 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/islandia.jpg'),
('Israel', 'Hebraico/Árabe', '9 milhões', 'Republica parlamentarista', '0,919', 'Isaac Herzog', 'Jerusalém', '501 Bi USD', 'Novo Shekel Israelense (ILS)', '22.145Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/125px-Flag_of_Israel.svg.png'),
('Itália', 'Roma', '59 milhões', 'Capitalista', '0.895', 'Sergio Mattarella', 'Italiano', '$2,2 trilhões', 'Euro (EUR)', '301.340 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/italia.jpg'),
('Jamaica', 'Kingston', '2,827 milhões', 'democracia parlamentar e monarquia constitucional', '0.688', 'Patrick Allen', 'Inglês', '17,1 bilhões USD', 'Dólar jamaicano', '10.991 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/125px-Flag_of_Jamaica.svg.png'),
('Japão', 'Japonês', '126 milhões', 'Monarquia constitucional', '0,919', 'Naruhito', 'Tóquio', '5 Tri USD', 'Iene (JP¥)', '377.975Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png'),
('Jordânia', 'Árabe', '10 milhões', 'Monarquia constitucional', '0,741', 'Abdullah II da Jordânia', 'Amã', '46 Bi USD', 'Dinar Jordaniano (JOD)', '89.342Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/125px-Flag_of_Jordan.svg.png'),
('Kiribati', 'Baikiti', '119,4 mil', 'República presidencialista', '0.624', 'Taneti Maamau', 'Inglês e gilbernês', ' 130 mi USD ', 'Dólar de Kiribati e Dólar Australiano', '726 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/1200px-Flag_of_Kiribati.svg.png'),
('Kuwait', 'Árabe', '4,3 milhões', 'Monarquia constitucional', '0,816', 'Mishal Al-Ahmad Al-Jaber Al-Sabah', 'Kuwait', '132 Bi USD', 'Dinar kuwaitiano (KD)', '17.818Km²', 'https://tse1.mm.bing.net/th?id=OIP.ktD7wm-W7zL9_MeluCa2nAHaDt&pid=Api&P=0&h=180'),
('Laos', 'Lao', '7,2 milhões', 'República socialista de partido único', '0,613', 'Thongloun Sisoulith', 'Vivenciana', '19 Bi USD', 'Kip laosiano (LAK)', '236.800Km²', 'https://tse1.mm.bing.net/th?id=OIP.T6-IOBXz6AB03l-6611lsgHaE8&pid=Api&P=0&h=180'),
('Lesoto', 'Maseru', '2.175.000', 'Monarquia constitucional parlamentarista', '0.527', 'Sam Matekane', 'Sesoto e Inglês', '2,947 bilhões USD', 'Loti', '30.355 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/255px-Flag_of_Lesotho.svg.png'),
('Letônia', 'Riga', '1,8 milhões', 'Capitalista', '0.866', 'Edgars Rinkēvičs', 'Letão', '$44 bilhões', 'Euro (EUR)', '64.589 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/letonia.jpg'),
('Líbano', 'Árabe/Francês', '6,8 milhões', 'Republica parlamentarista', '0,73O', 'Najib Mikati', 'Beirute', '18 Bi USD', 'Libra libanesa (LBP)', '10.452Km²', 'https://tse2.mm.bing.net/th?id=OIP.nXMnhi2Ncz1oLRJfLdGqAAHaE8&pid=Api&P=0&h=180'),
('Libéria', 'Monróvia', '5.193.000', 'República presidencialista', '0.481', 'George Weah', 'Inglês', '3,727 bilhões USD', 'Dólar liberiano', '111.369 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/255px-Flag_of_Liberia.svg.png'),
('Líbia', 'Trípoli', '7.079.000', 'Governo interino', '0.718', 'Mohamed al-Menfi', 'Árabe', '74,85 bilhões USD', 'Dinar líbio', '1.759.541 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/255px-Flag_of_Libya.svg.png'),
('Liechtenstein', 'Vaduz', '39 mil', 'Capitalista', '0.961', 'Alois von und zu Liechtenstein', 'Alemão', '$6,5 bilhões', 'Franco suíço (CHF)', '160 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/liechtenstein.jpg'),
('Lituânia', 'Vilnius', '2,6 milhões', 'Capitalista', '0.882', 'Gitanas Nausėda', 'Lituano', '$68 bilhões', 'Euro (EUR)', '65.300 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/lituania.jpg'),
('Luxemburgo', 'Luxemburgo', '634,814', 'Capitalista', '0.916', 'Henri, Grão-Duque de Luxemburgo', 'Luxemburguês', '$72,383 bilhões', 'Euro (EUR)', '2.586 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/luxemburgo.jpg'),
('Macedônia do Norte', 'Skopje', '2,083,374', 'Capitalista', '0.78', 'Stevo Pendarovski', 'Macedônio', '$6,260 bilhões', 'Dinar macedônio (MKD)', '25.713 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/macedonia.jpg'),
('Madagascar', 'Antananarivo', '30.370.000', 'República semipresidencialista', '0.502', 'Andry Rajoelina', 'Malgaxe e Francês', '13,72 bilhões USD', 'Ariary', '587.041 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/255px-Flag_of_Madagascar.svg.png'),
('Malásia', 'Malaio', '32 milhões', 'Monarquia constitucional federal', '0,807', 'Sultan Ibrahim', 'Kuala Lumpur', '373 Bi USD', 'Ringgit da Malásia (MYR)', '330.803Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/2800px-Flag_of_Malaysia.svg.png'),
('Malawi', 'Lilongué', '21.540.000', 'República presidencialista', '0.445', 'Lazarus Chakwera', 'Inglês e Chichewa', '12,63 bilhões USD', 'Kwacha malauiano', '118.484 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/255px-Flag_of_Malawi.svg.png'),
('Maldivas', 'Dhivehi', '540 mil', 'república presidencialista', '0,751', 'Mohamed Muizzu', 'Malé', '5,9 Bi USD', 'Rúpia madívia (MVR)', '298Km²', 'https://flagpedia.net/data/flags/w1600/mv.png'),
('Mali', 'Bamaco', '23.050.000', 'República presidencialista', '0.428', 'Assimi Goïta', 'Francês', '19,71 bilhões USD', 'Franco CFA Ocidental', '1.240.192 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/255px-Flag_of_Mali.svg.png'),
('Malta', 'Valletta', '514,564', 'Capitalista', '0.895', 'George Vella', 'Maltês', '$35,065 bilhões', 'Euro (EUR)', '316 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/malta.jpg'),
('Marrocos', 'Rabat', '37.760.000', 'Monarquia constitucional', '0.686', 'Aziz Akhannouch', 'Árabe e Berbere', '133,1 bilhões USD', 'Dirrã marroquino', '710.850 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/255px-Flag_of_Morocco.svg.png'),
('Martinica', 'Fort-de-France', '376.891', 'Estado Unitário, República Constitucional, Semipresidencialismo', '0.863', 'Emmanuel Macron', 'Francês', '6,117 milhões USD', 'Euro', '1.128 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag-of-Martinique.svg/125px-Flag-of-Martinique.svg.png'),
('Maurício', 'Port Louis', '1.266.000', 'República Parlamentarista', '0.802', 'Prithvirajsing Roopun', 'Inglês', '13,54 bilhões USD', 'Rupia mauriciana', '2.040 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/255px-Flag_of_Mauritius.svg.png'),
('Mauritânia', 'Nouakchott', '4.600.000', 'República presidencialista', '0.546', 'Mohamed Ould Ghazouani', 'Árabe', '8,17 bilhões USD', 'Ouguiya', '1.030.700 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/255px-Flag_of_Mauritania.svg.png'),
('México', 'Cidade do México', '127,5 milhões', 'Presidencialismo, República federal', '0.779', 'Andrés Manuel López Obrador', 'Espanhol', '1,466 trilhão USD ', 'Peso Mexicano', '1.973.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png'),
('Mianmar', 'Birmanês', '54 milhões', 'República parlamentarista sob governo militar', '0,451', 'não identificado', 'Nay Puy Taw', '65 Bi USD', 'Quiate (MMK)', '676.578Km²', 'https://cdn10.bigcommerce.com/s-hhbbk/products/707/images/38080/MYAN0001__31508.1580507643.1280.1280.png?c=2'),
('Moçambique', 'Maputo', '31.616.000', 'República presidencialista', '0.446', 'Filipe Nyusi', 'Português', '15,63 bilhões USD', 'Metical', '801.590 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/255px-Flag_of_Mozambique.svg.png'),
('Moldávia', 'Chisinau', '2,640,438', 'Capitalista', '0.741', 'Maia Sandu', 'Romeno', '$3,692 bilhões', 'Leu moldávio (MDL)', '33.846 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/moldavia.jpg'),
('Mônaco', 'Mônaco', '38,300', 'Capitalista', '0.96', 'Príncipe Albert II', 'Francês', '$7,165 bilhões', 'Euro (EUR)', '2.02 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/monaco.jpg'),
('Mongólia', 'Mongol', '3,3 milhões', 'República Semipresidencialista', '0,739', 'Ukhnaagiin Khurelsukh', 'Ulan Bator', '15 Mi USD', 'Tughrik mongol (MNT)', '1.564.116Km²', 'https://www.publicdomainpictures.net/pictures/340000/velka/flag-of-mongolia-1588674261S6f.jpg'),
('Montenegro', 'Podgorica', '622,359', 'Capitalista', '0.814', 'Milo Đukanović', 'Montenegrino', '$5,817 bilhões', 'Euro (EUR)', '13.812 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/montenegro.jpg'),
('Montserrat', 'Plymouth, Brades', '4.992', 'Monarquia Parlamentarista, Território Dependente', '0.958', 'Carlos III', 'Inglês', '43 milhões USD', 'Dólar do Caribe Oriental', '102 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/125px-Flag_of_Montserrat.svg.png'),
('Namíbia', 'Windhoek', '2.494.000', 'República presidencialista', '0.615', 'Hage Geingob', 'Inglês', '11,84 bilhões USD', 'Dólar namibiano', '825.615 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/255px-Flag_of_Namibia.svg.png'),
('Nauru', 'Yaren', '10,6 mil', 'República parlamentarista', '0.696', 'David Adeang', 'Nauruano e inglês', ' 60 mi USD ', 'Dólar australiano', '21 km²', 'https://img.freepik.com/vetores-premium/bandeira-de-nauru_628407-644.jpg?w=900'),
('Nepal', 'Nepalês', '30 milhões', 'República federal democrática', '0,428', 'Ram Chandra Paudel', 'Katmandu', '40,83 Bi USD', 'Rupia nepalesa', '147.181 km²', 'https://tse4.mm.bing.net/th?id=OIP.2p6Zt96_XWzZPPFzeIvsaAHaEK&pid=Api&P=0&h=180'),
('Nicarágua', 'Manágua', '6,948 milhões', 'República, Estado unitário, Presidencialismo', '0.667', 'Daniel Ortega', 'Espanhol', '15,67 bilhões USD', 'Córdoba nicaraguense', '130.373 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/800px-Flag_of_Nicaragua.svg.png'),
('Níger', 'Niamei', '25.160.000', 'República semipresidencialista', '0.4', 'Abdourahamane Tchiani', 'Francês', '14,92 bilhões USD', 'Franco CFA Ocidental', '1.267.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/255px-Flag_of_Niger.svg.png'),
('Nigéria', 'Abuja', '213.400.000', 'República presidencialista', '0.535', 'Bola Tinubu', 'Inglês', '514,1 bilhões USD', 'Naira', '923.769 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/255px-Flag_of_Nigeria.svg.png'),
('Noruega', 'Oslo', '5,432,580', 'Capitalista', '0.953', 'Harald V', 'Norueguês', '$398.854 bilhões', 'Coroa norueguesa (NOK)', '385,207 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/noruega.jpg'),
('Nova Zelândia', 'Wellington', '5,3 mi', 'Monarquia constitucional parlamentarista', '0.937', 'Rei Carlos III', 'Inglês, Maori', ' 279,2 bi USD ', 'Dólar da Nova Zelândia', '268 mil km²', 'https://img.freepik.com/vetores-gratis/ilustracao-da-bandeira-da-nova-zelandia_53876-27119.jpg?t=st=1723642255~exp=1723645855~hmac=4368722d4744b0af289aa9de0f99b1b7cb7d8de19cf920805bd67e923dda335a&w=1060'),
('Omã', 'Árabes', '4,576 milhões', 'Monarquia Absolutista', '0,813', 'Haitham bin Tariq Al Said', 'Mascate', '114,7 Bi USD', 'Rial omanense (OMR)', '309.501 km²', 'https://cidadeolimpica.com.br/wp-content/uploads/2022/01/bandeira-oma.png'),
('País de Gales', 'Cadiff', '3,1 milhões', 'Capitalista', '0.932', 'Rishi Sunak', 'Galês', '$90 bilhões', 'Libra esterlina (GBP)', '20.761 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/paisdegales.jpg'),
('Países Baixos', 'Amsterdã', '17,5 milhões', 'Capitalista', '0.944', 'Rei Willem-Alexander', 'Holandês', 'US$ 1,0 trilhão', 'Euro (EUR)', '41.543 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/holanda.jpg'),
('Palau', 'Melekeok', '20,8 mil', 'República presidencialista', '0.797', 'Surangel Whipps Jr.', 'Inglês, palauano, japonês, tobiado e sonsorolês', ' 182 mi USD', 'Dólar americano', '458 km²', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg'),
('Panamá', 'Cidade do Panamá', '4,409 milhões', 'República, Presidencialismo, Estado unitário democrático republica constitucional', '0.755', 'José Raúl Mulino', 'Espanhol', '76,52 bilhões', 'Dólar americano, Balboa panamenho', '75.517 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/125px-Flag_of_Panama.svg.png'),
('Papua-Nova Guiné', 'Port Moresby', '11,7 mi', 'Monarquia constitucional parlamentarista', '0.558', 'Rei Carlos III', 'Inglês, Hiri Motu e Tok Pisin', ' 8,2 bi USD ', 'Kina', '462 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/227px-Flag_of_Papua_New_Guinea.svg.png'),
('Paquistão', 'Urdu/Inglês', '235,8 milhões', 'Republica Federal', '0,537', 'Asif Ali Zardari', 'Islamabad', '374,7 Bi USD', 'Rupia paquistanesa (PKR)', '796 km²', 'https://www.paquistao.org/wp-content/uploads/2019/05/Cores-Bandeira-do-Paquistao.png'),
('Paraguai', 'Assunção', '6,781 milhões', 'República unitária presidencialista de partido dominante', '0.640', 'Santiago Peña', 'Espanhol', '41,72 Bilhões de Dólares', 'Guarani paraguaio', '406.752 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/188px-Flag_of_Paraguay.svg.png'),
('Peru', 'Lima', '34.05 milhões', 'República unitária presidencialista', '0.777', 'Dina Boluarte', 'Espanhol', '242.6 Bilhões de Dólares', 'Sol', '1.285 milhão km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/188px-Flag_of_Peru.svg.png'),
('Polinésia Francesa', 'Papeete', '280.208', 'Território dependente', '0,864', 'Moetai Brotherson', 'Francês', '5,623 milhões USD', 'franco CFP', '4.187 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/188px-Flag_of_French_Polynesia.svg.png'),
('Polônia', 'Varsóvia', '38 milhões', 'Capitalista', '0.88', 'Andrzej Duda', 'Polonês', 'US$ 656 bilhões', 'Zloty polonês (PLN)', '312.696 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/polonia.jpg'),
('Porto Rico', 'San Juan', '2 878 485 milhões', 'República, Democracia representativa, Presidencialismo', '0.865', 'Pedro Pierluisi', 'Espanhol, Inglês', '113,4 bilhões USD', 'Dólar americano', '13.791 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/800px-Flag_of_Puerto_Rico.svg.png'),
('Portugal', 'Lisboa', '10,2 milhões', 'Capitalista', '0.869', 'Marcelo Rebelo de Sousa', 'Português', 'US$ 367 bilhões', 'Euro (EUR)', '92.212 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/portugal.jpg'),
('Quênia', 'Nairóbi', '54.770.000', 'República presidencialista', '0.579', 'William Ruto', 'Suaíli e Inglês', '119,4 bilhões USD', 'Xelim queniano', '580.367 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/255px-Flag_of_Kenya.svg.png'),
('Quirguistão', 'Quirguiz/Russo', '6,6 milhões', 'Republica parlamentarista', '0,697', 'Sadyr Japarov', 'Bishkek', '8,5 Mi USD', 'Som quirguiz', '199.951Km²', 'https://tse4.mm.bing.net/th?id=OIP.FW_P-fBhZ4lRL07YYUtaawHaEc&pid=Api&P=0&h=180'),
('República Centro-Africana', 'Bangui', '5.508.000', 'República presidencialista unitária', '0.394', 'Faustin-Archange Touadéra', 'Francês e Sango', '2,255 bilhões USD', 'Franco CFA Central', '622.984 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/255px-Flag_of_the_Central_African_Republic.svg.png'),
('República Democrática do Congo', 'Kinshasa', '99.010.000', 'República semipresidencialista', '0.481', 'Félix Tshisekedi', 'Francês', '64,72 bilhões USD', 'Franco congolês', '2.345.000 km²', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg'),
('República do Congo', 'Brazavile', '5.677.49', 'República Semipresidencialista Unitária de Partido Dominante', '0,571', 'Denis Sassou-Nguesso', 'Francês', '27,994 bilhões USD', 'Franco CFA', '342 000 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/188px-Flag_of_the_Republic_of_the_Congo.svg.png'),
('República Dominicana', 'Santo Domingo', '11,23 milhões', 'Presidencialista unitário', '0.767', 'Luis Abinader', 'Espanhol', '113,5 bilhões', 'Peso dominicano', '48.442 km²', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg'),
('Romênia', 'Bucareste', '19 milhões', 'Capitalista', '0.821', 'Klaus Iohannis', 'Romeno', '$284 bilhões', 'Leu romeno (RON)', '238.397 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/romenia.jpg'),
('Ruanda', 'Quigali', '13.260.000', 'República presidencialista', '0.543', 'Paul Kagame', 'Kinyarwanda, Francês e Inglês', '11,07 bilhões USD', 'Franco ruandês', '26.338 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/255px-Flag_of_Rwanda.svg.png'),
('Rússia', 'Russo', '143 milhões', 'república federal semipresidencialista', '0,824', 'Vladimir Putin', 'Moscou', '1,7 Tri USD', 'Rublo russo (RUB)', '17.098.242Km²', 'https://tse2.mm.bing.net/th?id=OIP.uW9Hi1USsULyX2e4Y7iy-gAAAA&pid=Api&P=0&h=180'),
('Saara Ocidental', 'El Aiune', '567.402', 'República nominal', '0,500', 'Brahim Ghali', 'Árabe e espanhol', '900 milhões USD', 'dirrã marroquino peseta saaraui', '266.719 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/188px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png'),
('Samoa', 'Ápia', '176,2 mil', 'República parlamentarista', '0.707', 'Va\'aletoa Sualauvi II', 'Inglês e samoano', ' 523 mi USD ', 'Tala', '2 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/1200px-Flag_of_Samoa.svg.png'),
('Samoa Americana', 'Pago Pago', '46.366', 'Território não incorporado', '0,707', 'Lemanu Peleti Mauga', 'Samoano e inglês', '575,3 milhões USD', 'Dólar americano', '199 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/188px-Flag_of_American_Samoa.svg.png'),
('San Marino', 'San Marino', '34 mil', 'Capitalista', '0.853', 'Alessandro Scarano', 'Italiano', '$1,64 bilhões', 'Euro (EUR)', '61 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/sanmarino.jpg'),
('Santa Lucia', 'Castries', '179.857', 'Monarquia Parlamentarista', '0.715', 'Charles III', 'Inglês', '2,3 bilhões USD', 'Dólar do Caribe Oriental', '617 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/800px-Flag_of_Saint_Lucia.svg.png'),
('Santo Kitts e Nevis', 'Basseterre', '147.657', 'Federação, Parlamentarismo, Monarquia Parlamentarista, Monarquia Constitucional Federal', '0.838', 'Timothy Harris', 'Inglês', '965,6 milhões USD ', 'Dólar do Caribe Oriental', '261 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/1024px-Flag_of_Saint_Kitts_and_Nevis.svg.png'),
('São Bartolomeu', 'Gustávia', '9.131', 'República Presidencialista', '0.901', 'Emmanuel Macron', 'Francês', '26 mil USD', 'Euro', '21 km²', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg'),
('São Tomé e Príncipe', 'São Tomé', '231.000', 'República semipresidencialista', '0.618', 'Carlos Vila Nova', 'Português', '527 milhões USD', 'Dobra', '964 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/188px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png.svg.png'),
('São Vicente e Granadina', 'Kingstown', '103.948', 'Democracia Parlamentar e Monarquia Constitucional', '0.755', 'Charles III', 'Inglês', '948,6 milhões USD', 'Dólar do Caribe Oriental', '389 km²', 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg'),
('Senegal', 'Dacar', '17.690.000', 'República semipresidencialista', '0.535', 'Macky Sall', 'Francês', '27,33 bilhões USD', 'Franco CFA Ocidental', '196.722 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/255px-Flag_of_Senegal.svg.png'),
('Serra Leoa', 'Freetown', '8.240.000', 'República presidencialista', '0.452', 'Julius Maada Bio', 'Inglês', '4,099 bilhões USD', 'Leone', '71.740 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/255px-Flag_of_Sierra_Leone.svg.png');
INSERT INTO `paises` (`nome`, `capital`, `populacao`, `politica`, `idh`, `presidente`, `idioma`, `pib`, `moeda`, `territorio`, `bandeira`) VALUES
('Sérvia', 'Belgrado', '6,7 milhões', 'Capitalista', '0.806', 'Aleksandar Vučić', 'Sérvio', '$65 bilhões', 'Dinar sérvio (RSD)', '88.361 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/servia.jpg'),
('Singapura', 'Inglês/Malaio', '5,7 milhões', 'República parlamentarista', '0,939', 'Tharman Shanmugaratnam', 'Cingapura', '396 Bi USD', 'SGD', '728Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/125px-Flag_of_Singapore.svg.png'),
('Sint Maarten', 'Phillipsburg', '42.848', 'Monarquia Parlamentarista, Estado Unitário, Democracia Representativa', 'não classificado', 'Guilherme Alexandre', 'Neerlandês, Inglês', '1,537 bilhão USD', 'Florim das Antilhas Holandesa', '34 km²', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Sint_Maarten.svg'),
('Síria', 'Árabe', '17,5 milhões', 'Republica presidencialista autoritária', '0,549', 'Bashar al-Assad', 'Damasco', '21 Bi USD', 'Libra síria (SYP)', '185.180Km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/125px-Flag_of_Syria.svg.png'),
('Somália', 'Mogadíscio', '17.470.000', 'República parlamentarista federal', '0.383', 'Hassan Sheikh Mohamud', 'Somali', '7,209 bilhões USD', 'Xelim somali', '637.657 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/255px-Flag_of_Somalia.svg.png'),
('Sri Lanka', 'Cingalês/Tâmil', '21 milhões', 'Republica presidencialista', '0,782', 'Ranil Wickremesinghe', 'Kotte', '84 Mi USD', 'Rupia cingalesa (LKR)', '65.610Km²', 'https://wallpaperaccess.com/full/2714480.jpg'),
('Suazilândia', 'Mbabane', '1.093.000', 'Monarquia absoluta', '0.608', 'Mswati III', 'Inglês e Suázi', '4,714 bilhões USD', 'Lilangeni', '17.364 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/255px-Flag_of_Eswatini.svg.png'),
('Sudão', 'Cartum', '47.850.000', 'República presidencialista', '0.512', 'Abdel Fattah al-Burhan', 'Árabe e Inglês', '26,39 bilhões USD', 'Libra sudanesa', '1.886.068 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/255px-Flag_of_Sudan.svg.png'),
('Sudão do Sul', 'Juba', '10.750.000', 'República presidencialista', '0.385', 'Salva Kiir Mayardit', 'Inglês', '1,691 bilhões USD', 'Libra sul-sudanesa', '619.745 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/255px-Flag_of_South_Sudan.svg.png'),
('Suécia', 'Estocolmo', '10,4 milhões', 'Capitalista', '0.945', 'Magdalena Andersson', 'Sueco', '$635 bilhões', 'Coroa sueca (SEK)', '450.295 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/suecia.jpg'),
('Suíça', 'Berna', '8,7 milhões', 'Capitalista', '0.955', 'Alain Berset', 'Alemão', '$813 bilhões', 'Franco suíço (CHF)', '41.285 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/suica.jpg'),
('Suriname', 'Paramaribo', '618.040 ', 'República com poder executivo vinculado ao parlamento unitária', '0.646', 'Chandrikapersad Santokhi', 'Holandês', '3,621 Bilhões de Dólares', 'Dólar surinamês', '176.215 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/188px-Flag_of_Suriname.svg.png'),
('Tailândia', 'Tailandês', '70 milhões', 'Monarquia constitucional', '0,800', 'Maha Vajiralongkorn', 'Bangkok', '543 Bi USD', 'Baht tailandês (THB)', '513.120Km²', 'https://pixelz.cc/wp-content/uploads/2018/11/tajikistan-flag-uhd-4k-wallpaper.jpg'),
('Taiwan', 'Taipé', '23 milhões', 'República semipresidencialista unitária', '0,885', 'Lai Ching-te', 'Mandarim', '1,404 trilhão USD', 'Novo dólar taiwanês', '35.980 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/125px-Flag_of_the_Republic_of_China.svg.png'),
('Tajiquistão', 'Tajique', '9,5 milhões', 'república presidencialista', '0,668', 'Emomali Rahmon', 'Dushanbe', '8 Mi USD', 'Somoni (TJS)', '143.100Km²', 'https://pixelz.cc/wp-content/uploads/2018/11/tajikistan-flag-uhd-4k-wallpaper.jpg'),
('Tanzânia', 'Dodoma', '67.780.000', 'República presidencialista', '0.529', 'Samia Suluhu', 'Suaíli e Inglês', '85,42 bilhões USD', 'Xelim tanzaniano', '947.303 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/255px-Flag_of_Tanzania.svg.png'),
('Tchéquia', 'Praga', '10,5 milhões', 'Capitalista', '0.888', 'Petr Pavel', 'Checo', '$276 bilhões', 'Coroa checa (CZK)', '78.867 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/repcheca.jpg'),
('Timor-Leste', 'Tétum/Pt', '1,3 milhões', 'Republica presidencialista', '0,626', 'José Manuel Ramos-Horta', 'Dili', '2,5 Mi USD', 'Dólar americano (USD)', '15.007Km²', 'https://tse2.mm.bing.net/th?id=OIP.KL1owDQTewJdnxgGokVtFgHaDt&pid=Api&P=0&h=180'),
('Togo', 'Lomé', '9.117.000', 'República semipresidencialista', '0.515', 'Faure Gnassingbé', 'Francês', '8,767 bilhões USD', 'Franco CFA Ocidental', '56.785 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/255px-Flag_of_Togo.svg.png'),
('Tonga', 'Nocualofa', '100,6 mil', 'Monarquia constitucional parlamentarista', '0.745', 'Rei Tupou VI', 'Tonganês e inglês', ' 801 mi USD ', 'Pa\'anga', '462 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg'),
('Tunísia', 'Túnis', '12.356.000', 'República semipresidencialista', '0.733', 'Kais Saied', 'Árabe', '47,68 bilhões USD', 'Dinar tunisiano', '163.610 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/255px-Flag_of_Tunisia.svg.png'),
('Turcomenistão', 'Turcomeno', '6,2 milhões', 'Republica presidencialista autoritária', '0,715', 'Serdar Berdimuhamedow', 'Asgabate', '4,5 Mi USD', 'Manat turcomano (TMM)', '491.210Km²', 'https://flagpedia.net/data/flags/w1600/tm.png'),
('Turquia', 'Ancara', '84 milhões', 'Capitalista', '0.838', 'Recep Tayyip Erdoğan', 'Turco', '$815 bilhões', 'Lira turca (TRY)', '783.562 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1200px-Flag_of_Turkey.svg.png'),
('Tuvalu', 'Funafui', '11,3 mil', 'Monarquia constitucional parlamentarista', '0.590', 'Rei Carlos III', 'Tuvaluano e inglês', ' 86,4 mi USD ', 'Dólar tuvaluano e dólar australiano', '26 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/1200px-Flag_of_Tuvalu.svg.png'),
('Ucrânia', 'Kiev', '41 milhões', 'Capitalista', '0.773', 'Volodymyr Zelensky', 'Ucraniano', '$200 bilhões', 'Hryvnia (UAH)', '603.628 km²', 'https://www.sogeografia.com.br/figuras/bandeiras/europa/ucrania.jpg'),
('Uganda', 'Campala', '48.690.000', 'República presidencialista', '0.528', 'Yoweri Museveni', 'Inglês e Suaíli', '48,52 bilhões USD', 'Xelim ugandense', '241.038 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/255px-Flag_of_Uganda.svg.png'),
('Uruguai', 'Montevidéu', '3,423 milhões', 'República presidencialista unitária', '0.830', 'Luis Alberto Lacalle Pou', 'Espanhol', '71,18 Bilhões de Dólares', 'Peso uruguaio', '176.215 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/188px-Flag_of_Uruguay.svg.png'),
('Uzbequistão', 'Uzbeque', '34 milhões', 'Republica presidencialista autoritária', '0,720', 'Shavkat Mirziyayev', 'Tashkent', '80 Bi USD', 'Som uzbeque (UZS)', '447.400Km²', 'http://s1.bwallpapers.com/wallpapers/2014/05/29/uzbekistan-flag_121436716.jpg'),
('Vanuatu', 'Port Vila', '272,4 mil', 'República parlamentarista', '0.607', 'Nikenike Vurobaravu', 'bislamá, inglês e francês', ' 574 mi USD ', 'vatu', '11 mil km²', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg'),
('Venezuela', 'Caracas', '28.3 milhões', 'República federal presidencialista', '0.699', 'Nicolás Maduro', 'Espanhol', '92,21 Bilhões de Dólares', 'Bolívar soberano', '916,445 km2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/188px-Flag_of_Venezuela.svg.png'),
('Vietnã', 'Vietnamita', '99 milhões', 'Republica socialista de partido único', '0,704', 'To Lam', 'Hanói', '408 Bi USD', 'Dong vietnamita (VND)', '331.212Km²', 'https://www.worldatlas.com/upload/a6/4c/2e/vn-flag.jpg'),
('Zâmbia', 'Lusaca', '20.580.000', 'República presidencialista', '0.592', 'Hakainde Hichilema', 'Inglês', '27,63 bilhões USD', 'Kwacha zambiano', '752.612 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/255px-Flag_of_Zambia.svg.png'),
('Zimbábue', 'Harare', '15.280.000', 'República presidencialista', '0.593', 'Emmerson Mnangagwa', 'Inglês', '26,25 bilhões USD', 'Dólar zimbabuano', '390.757 km²', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/255px-Flag_of_Zimbabwe.svg.png');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `paises`
--
ALTER TABLE `paises`
  ADD PRIMARY KEY (`nome`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
